version: "3"

x-tina4-login-common-variables:
  &tina4-login-common-variables
  BASE_URL: 'http://localhost:7145'
  REDIS_HOST: redis
  REDIS_PORT: 6379
  DEFAULT_USER_TOKEN_EXPIRY_DAYS: 1
  TINA4_SERVICE_TIME: 60
  SSO_TOKEN: '37848C11-A4A8-46A6-90D4-C145778CD7C8'
  SSO_REDIRECT_URL: 'aHR0cDovLzEyNy4wLjAuMTo3Nzc3L3Nzby1sb2dpbg'
  SSO_BASE_TWIG_FILE: 'tina4Login-base.twig'

services:
  app:
    container_name: tina4_login
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      <<: *tina4-login-common-variables
    ports:
      - "1234:7145"
    volumes:
      - ../:/var/www/html
    networks:
      - internal

networks:
  internal:

volumes:
  tina4-jobs-db-data:


